### PR TITLE
Add snake game

### PR DESCRIPTION
**Pull request by prakamya-mishra**
This is with reference to #10 .

### CODE REVIEW

**Comment by pulkonet** [comment]
You weren't assigned to this issue. Please close your PR.

**Comment by prakamya-mishra** [comment]
I thought the readme file can have many list of users thats why I gave this PR. What should I do @mishal23

**Comment by mishal23** [comment]
@pulkonet That is fine, you may also, send a PR with your project. We are looking for all the projects of that kind.
So feel free to send a PR

**Comment by mishal23** [comment]
@prakamya-mishra Done close the PR, yes many of them can be there.

**Pull request merged**
